name: unit_test
on:
  push:
    paths:
      - '**.cpp'
      - '**.h'
      - 'test/*'
      - 'meson.build'
      - '.github/workflows/*'
  pull_request:
    paths:
      - '**.cpp'
      - '**.h'
      - 'test/*'
      - 'meson.build'
      - '.github/workflows/*'

jobs:
  unit_test:
    permissions:
      contents: read
    runs-on: ubuntu-latest
    strategy:
      matrix:
        version: [11, 20]
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install meson
        run: sudo apt-get install meson

      - name: Setup
        run: meson setup build -Dcpp_std=c++${{ matrix.version }}

      - name: Compile
        working-directory: build
        run: meson compile

      - name: Run Test
        working-directory: build
        run: meson test
